name: Android Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create apikey.properties
        run: |
          cat <<EOF> apikey.properties
          API_KEY = "API_KEY"
          ALGOLIA_API_KEY = "ALGOLIA_API_KEY"
          ALGOLIA_APP_ID = "ALGOLIA_APP_ID"
          EOF

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
         java-version: 1.8

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble