name: Android Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create apikey.properties
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: "apikey.properties"
          FILE_DATA: "API_KEY=""\nALGOLIA_API_KEY=""\nALGOLIA_APP_ID="""

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
         java-version: 1.8

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble